Makeup layout Резиновый макет Задание 1
RuslanIbragimov5/admin-panel-makeup pull request #1
Opened 2022-01-18 18:02 UTC by RuslanIbragimov5

2022-01-19 21:43 UTC, Muslik approved these changes
Классная работа. Добавьте padding родительскому блоку вместо margin-а каждому внутреннему по отдельности.

2022-01-19 21:43 UTC, Muslik commented on index.html
> +      <div class="table-header">
Ну тут наверное class="table" лучше подойдет, а то ниже "table-header__header" выглядит странно )

2022-01-19 21:43 UTC, Muslik commented on style.css
> +  margin: 8px 8px;
Не должно быть margin-ов у каждого блока по отдельности. У вас есть блок обертка - fliter-row. У него должен быть padding сверху, снизу. У блоков внутри будут только отступы друг относительно друга.

2022-01-19 23:25 UTC, Muslik commented on style.css
> +  margin: 32px 0px;
У блока по БЭМ не должно быть отступов. Они должны быть у элементов.

И тогда у filter-row будет два класса: <div class="filter-row container__filter-row"></div>

В таком случае мы можем основные стили задать блоку .filter-row, а его отступы (margin) указать в классе container__filter-row. И получается что filter-row является блоком сам по себе, но в контексте данной страницы он является еще и элементом

2022-01-22 10:18 UTC, RuslanIbragimov5 commented on index.html
> +      <div class="table-header">
действительно) исправил

2022-01-22 10:22 UTC, RuslanIbragimov5 commented on style.css
> +  margin: 8px 8px;
Джабраил, посмотри пожалуйста, я добавил padding filter-row, но у filter-button остался margin, это нормально?

2022-01-22 10:29 UTC, RuslanIbragimov5 commented on style.css
> +  margin: 32px 0px;
добавил margin в классе container__filter-row.

2022-01-22 17:00 UTC, Muslik requested changes

2022-01-22 17:00 UTC, Muslik commented on index.html
> +        <h1 class="page-header__page-name">Page header</h1>
Цвет текста не как на макете

2022-01-22 17:00 UTC, Muslik commented on style.css
> +  margin: 0px 8px;
margin справа не нужен

2022-01-22 17:00 UTC, Muslik commented on index.html
> +        <div class="table__body"></div>
body должен занимать всю высоту вниз как на макете

2022-01-22 17:01 UTC, Muslik commented on style.css
> +  margin: 8px 8px;
Нормально

2022-01-22 20:54 UTC, RuslanIbragimov5 commented on index.html
> +        <h1 class="page-header__page-name">Page header</h1>
исправлено

2022-01-22 20:54 UTC, RuslanIbragimov5 commented on style.css
> +  margin: 0px 8px;
Убрал

2022-01-22 20:54 UTC, RuslanIbragimov5 commented on index.html
> +        <div class="table__body"></div>
исправлено

2022-01-23 13:16 UTC, Muslik approved these changes

2022-01-23 15:34 UTC, merged