Makeup input дз 3
RuslanIbragimov5/admin-panel-makeup pull request #4
Opened 2022-01-30 19:40 UTC by RuslanIbragimov5

https://ruslanibragimov5.github.io/admin-panel-makeup/ui-kit.html
Добавлю обязательно всё после проверки в папку blocks. Наконец-то он отобразился на странице

2022-01-30 20:06 UTC, RuslanIbragimov5 commented
https://ruslanibragimov5.github.io/admin-panel-makeup/pages/blocks/ui-kit.html
Когда отправлял ссылку, не отображались стили. Надеюсь при проверке всё будет норм

2022-01-30 20:27 UTC, RuslanIbragimov5 commented
Всё отображается)

2022-02-01 20:28 UTC, Muslik requested changes
Поработать с именованием классов... Привести в порядок отступы. Привести в соответствии с дизайном

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/ui-kit.html
> +              class="button-form_x-medium"
Класс не по БЭМ

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/ui-kit.html
> +            <svg
Это должна быть кнопка.

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/input.css
> +html,
Шрифт не по макету. Иконки не по макету. В последний инпут я могу установить фокус. (такого быть не должно)

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/ui-kit.html
> +        <div class="input-rows__input-empty">
Мне очень не нравится именование классов. Это вообще не инпут. Зачем ему такой класс? В css ничего не обнаружил.

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/ui-kit.html
> +          <label for="emptyForm" class="input-empty__date"
Это же не date. Это input...

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/ui-kit.html
> +          <label for="emptyForm" class="input-empty__date"
Например:
```html
<div class="form-row">
  <label class="label" />
  <div class="input-wrapper">
    <input class="input" />
  </div>
</div>
```

Сразу понятно где есть что. Если мне надо сделать стили для ошибочного стиля, то добавлю модификатор class="input input_error"

2022-02-01 20:28 UTC, Muslik commented on pages/blocks/input.css
> +.body {
Странные margin-ы. Зачем margin-top у label ? Зачем margin-bottom у input

2022-02-01 21:01 UTC, RuslanIbragimov5 commented on pages/blocks/input.css
> +html,
Шрифт согласен. Фокус уберу. Иконки брал с папки icons. Проводил через конвертер SVG. Так нельзя?

2022-02-01 21:42 UTC, RuslanIbragimov5 commented on pages/blocks/input.css
> +.body {
Это было указано согласно макета. Понял, что ошибка дизайнера. Исправлю. Только нужно время

2022-02-01 21:42 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +          <label for="emptyForm" class="input-empty__date"
Принято

2022-02-01 21:43 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +        <div class="input-rows__input-empty">
Принято

2022-02-04 23:33 UTC, Muslik requested changes
Крестик немного криво выровнен. Отступ справа побольше нужен. Сам крестик должен быть кнопкой, а замочек просто иконкой. Последний input должен быть disabled а не readonly (Проверьте цвет шрифта после того как поменяете) иначе сейчас в него можно поставить фокус.

2022-02-04 23:33 UTC, Muslik commented on pages/blocks/ui-kit.html
> +                class="button-form_locked"
Почему class button если это иконка?

2022-02-05 13:55 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +                class="button-form_locked"
https://ruslanibragimov5.github.io/admin-panel-makeup/pages/blocks/ui-kit.html
Джабраил, проверь пожалуйста, теперь хорошо?

2022-02-05 14:28 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +            <svg
Переделал

2022-02-12 17:39 UTC, Muslik commented on pages/blocks/ui-kit.html
> +                class="button-form_locked"
Размер шрифта еще поправить нужно и font-family

2022-02-12 17:40 UTC, Muslik commented
opacity в крестике не нужен.

2022-02-12 17:41 UTC, Muslik approved these changes

2022-02-12 19:04 UTC, closed without merging