searchbar дз 4
RuslanIbragimov5/admin-panel-makeup pull request #5
Opened 2022-02-05 22:00 UTC by RuslanIbragimov5

https://ruslanibragimov5.github.io/admin-panel-makeup/pages/blocks/ui-kit.html

2022-02-08 17:21 UTC, Muslik requested changes
Требуются доработки

2022-02-08 17:21 UTC, Muslik commented on pages/blocks/search-bar.css
> +  padding: 8px 36px 8px 32px;
Padding всегда будет одинаковым. А значит не нужно два разных класса. Этот padding назначьте row__form

2022-02-08 17:21 UTC, Muslik commented on pages/blocks/ui-kit.html
> +        <button class="searchbar-button">
Иконка поиска - просто иконка. Крестик - кнопка с иконокой, но абсолютно позиционировать нужно родителя (то есть кнопку). Иначе ситуация такая что кнопки даже нет. https://ibb.co/HV2CKkd

2022-02-08 17:56 UTC, RuslanIbragimov5 commented on pages/blocks/search-bar.css
> +  padding: 8px 36px 8px 32px;
исправил

2022-02-08 20:12 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +        <button class="searchbar-button">
Исправил

2022-02-12 17:39 UTC, Muslik approved these changes
Замечания исправить.

2022-02-12 17:39 UTC, Muslik commented on pages/blocks/input.css
> +  opacity: 0.3;
Это не нужно...

2022-02-12 17:39 UTC, Muslik commented on pages/blocks/input.css
> +  padding: 8px 32px 8px 8px;
У body задайте font family как на макете. Размер шрифта в инпутах другой

2022-02-12 18:45 UTC, RuslanIbragimov5 commented on pages/blocks/input.css
> +  opacity: 0.3;
Исправил

2022-02-12 18:45 UTC, RuslanIbragimov5 commented on pages/blocks/input.css
> +  padding: 8px 32px 8px 8px;
Исправил

2022-02-12 18:58 UTC, merged