дз 7 dropdown
RuslanIbragimov5/admin-panel-makeup pull request #8
Opened 2022-02-23 19:55 UTC by RuslanIbragimov5

https://ruslanibragimov5.github.io/admin-panel-makeup/pages/blocks/ui-kit.html

2022-03-04 07:18 UTC, Muslik requested changes

2022-03-04 07:18 UTC, Muslik commented on pages/blocks/ui-kit.html
> +              class="button button_theme_secondary button_size_small button_width-full buttons-space__button"
Не может быть тут класса buttons-space__button. Нет родителя buttons-space

2022-03-04 07:18 UTC, Muslik commented on pages/blocks/ui-kit.html
> +              <input
Нужно использовать input который вы верстали ранее

2022-03-04 07:18 UTC, Muslik commented on pages/blocks/ui-kit.html
> +              <label class="checkbox__label" for="checkboxConfirmed"
В figma этот блок тянется на всю ширину. У вас между строками есть отступ: https://ibb.co/wJC4bxL. Соответственно я могу кликнуть в пустое место между блоками и ничего не произойдет. Используйте padding

2022-03-04 07:18 UTC, Muslik commented on pages/blocks/ui-kit.html
> +              <label class="checkbox__label" for="checkboxConfirmed"
С radio тоже самое

2022-03-07 13:43 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +              <input
исправил

2022-03-07 13:43 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +              class="button button_theme_secondary button_size_small button_width-full buttons-space__button"
Исправил

2022-03-07 13:43 UTC, RuslanIbragimov5 commented on pages/blocks/ui-kit.html
> +              <label class="checkbox__label" for="checkboxConfirmed"
Исправил

2022-03-08 20:56 UTC, Muslik approved these changes
Исправить замечание

2022-03-08 20:56 UTC, Muslik commented on pages/blocks/dropdown.css
> +  margin-bottom: 6px;
Не может быть модификатора который задает отступ. Это должен быть элемент по БЭМ

2022-03-09 18:36 UTC, RuslanIbragimov5 commented on pages/blocks/dropdown.css
> +  margin-bottom: 6px;
Исправил, так правильно?

2022-04-06 14:56 UTC, merged